image_width: 1280
image_height: 720
cells:
  - {cell_id: 1, x_min: 0, x_max: 319, y_min: 0, y_max: 179}
  - {cell_id: 2, x_min: 320, x_max: 639, y_min: 0, y_max: 179}
  - {cell_id: 3, x_min: 640, x_max: 959, y_min: 0, y_max: 179}
  - {cell_id: 4, x_min: 960, x_max: 1279, y_min: 0, y_max: 179}
  - {cell_id: 5, x_min: 0, x_max: 319, y_min: 180, y_max: 359}
  - {cell_id: 6, x_min: 320, x_max: 639, y_min: 180, y_max: 359}
  - {cell_id: 7, x_min: 640, x_max: 959, y_min: 180, y_max: 359}
  - {cell_id: 8, x_min: 960, x_max: 1279, y_min: 180, y_max: 359}
  - {cell_id: 9, x_min: 0, x_max: 319, y_min: 360, y_max: 539}
  - {cell_id: 10, x_min: 320, x_max: 639, y_min: 360, y_max: 539}
  - {cell_id: 11, x_min: 640, x_max: 959, y_min: 360, y_max: 539}
  - {cell_id: 12, x_min: 960, x_max: 1279, y_min: 360, y_max: 539}
